(specifications->manifest
 '("emacs-native-comp"
   "the-silver-searcher"
   "ripgrep"
   "emacs-vterm"
   "hledger"
   "imagemagick"
   "yt-dlp"
   "mpv"
   "graphviz"
   "emacs-emacsql-sqlite3"
   "python-isort"
   "python-yapf"
   "plantuml"))
