(specifications->manifest
 '("emacs-native-comp"
   "the-silver-searcher"
   "ripgrep"
   "emacs-vterm"
   "imagemagick"
   "youtube-dl"
   "mpv"
   "python-isort"
   "python-yapf"
   "graphviz"
   "emacs-emacsql-sqlite3"))
