#+TITLE: Arch Linux
#+PROPERTY: header-args :mkdirp yes

I've decided to switch to [[https://archlinux.org/][Arch Linux]] and configure it declaratively with [[https://github.com/ripytide/metapac][metapac]].

* System installation
** Installation
On installation, see https://wiki.archlinux.org/title/Installation_guide and/or use =archinstall=.

Don't forget to run
#+begin_src bash
pacman -Sy archlinux-keyring
#+end_src
Before =archinstall=.

** After installation
Update everything:
#+begin_src bash
sudo pacman -Syyu
#+end_src

Install git, python and yadm:
#+begin_src bash
sudo pacman -Syu python git pacman-contrib yadm
#+end_src

Select top-6 fastest mirrors to work with. Generate a mirrorlist file using this service: https://archlinux.org/mirrorlist/, then use =rankmirrors= from =pacman-contrib= (see [[https://wiki.archlinux.org/title/Mirrors][Mirrors]] on Arch Wiki).
#+begin_src bash
sudo -i
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist
#+end_src

If there isn't enough RAM (e.g. running in a VM), turn off mounting =/tmp= as [[https://wiki.archlinux.org/title/Tmpfs#Disable_automatic_mount][tmpfs]]:
#+begin_src basd
sudo systemctl mask tmp.mount
#+end_src

Install [[https://github.com/Morganamilo/paru][paru]]:
#+begin_src bash
sudo pacman -S --needed base-devel
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
#+end_src

Install [[https://github.com/ripytide/metapac][metapac]]:

#+begin_src bash
paru -Syyu metapac
#+end_src

Enable [[https://wiki.archlinux.org/title/Official_repositories#multilib][multilib]] by uncommenting the =[multilib]= section in =/etc/pacman.conf=.

Then install Arch packages with =metapac=:
#+begin_src bash
mkdir ~/00-Scratch/
git clone https://github.com/SqrtMinusOne/dotfiles.git ~/00-Scratch/dotfiles/
cp -r ~/00-Scratch/dotfiles/.config/metapac ~/.config/
metapac s
#+end_src

Then, install the ssh and gpg keys (put them into the =~/.ssh= folder). To export gpg keys:
#+begin_src bash
gpg --output private.pgp --armor --export-secret-keys <keyname>
#+end_src

And to import:
#+begin_src bash
gpg --import private.pgp
gpg --edit-key <keyname>
trust
#+end_src

Also the following to =~/.ssh/config=:
#+begin_src conf-space
Host *
    AddKeysToAgent yes
#+end_src

And run:
#+begin_src bash
systemctl enable --user --now ssh-agent
#+end_src
It looks like it is necessary to run at least once.

Then, clone the dotfiles repo with =yadm=:
#+begin_src bash
yadm clone git@github.com:SqrtMinusOne/dotfiles.git
#+end_src
Checkout the changed files.

Clone org-mode and passwords repos:
#+begin_src bash
git clone ssh://git@git.sqrtminusone.xyz:222/sqrtminusone/org-mode.git "/home/pavel/30-39 Life/32 org-mode"
git clone ssh://git@git.sqrtminusone.xyz:222/sqrtminusone/passwords.git "/home/pavel/.password-store"
#+end_src

And don't forget to configure git:
#+begin_src bash
git config --global user.email "thexcloud@gmail.com"
git config --global user.name "SqrtMinusOne"
#+end_src

#+begin_src bash
sudo systemctl enable --now NetworkManager
#+end_src

Install wakatime:
#+begin_src bash
cd ~/00-Scratch/
git clone https://github.com/wakatime/wakatime-cli.git
cd ./wakatime-cli
go build
mv wakatime-cli ~/bin
#+end_src

And create the =~/.wakatime.cfg= file with the following contents:
#+begin_src
[settings]
api_key = <api-key>
#+end_src

Then run =emacs= and make sure it starts. Run:
- =M-x nerd-icons-install-fonts=
- =M-x all-the-icons-install-fonts=
- =M-x treesit-install-language-grammar=

Run =rclone config=, configure the remotes. Then =M-x my/index-commands-sync=.

If everything works, login into EXWM.

Create some directories:
#+begin_src bash
mkdir -p /home/pavel/Pictures/screenshots/
mkdir -p /home/pavel/.mpd/playlists/
#+end_src

Also run:
#+begin_src bash
sudo chmod +s /usr/bin/light
#+end_src

For I've decided to use =NetworkManager=, but Arch Linux uses =iwd= by default, which causes issues. Disable it by:
#+begin_src bash
sudo systemctl disable --now iwd
sudo systemctl disable --now systemd-networkd
#+end_src
And reboot. After the reboot, =NetworkManager= should run using =wpa_supplicant= as backend for Wi-Fi.

Don't forget to sync mail and enable the sync timer.

#+begin_src bash
sudo usermod -a -G libvirt pavel
sudo usermod -a -G kvm pavel
#+end_src

Install [[https://github.com/retorquere/zotero-better-bibtex][zotero-better-bibtex]] manually.

Run =init-nvm=:
#+begin_src bash
bash /usr/share/nvm/init-nvm.sh
#+end_src

Add flatpak remote:
#+begin_src bash
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#+end_src

* Metapac configuration
[[https://github.com/ripytide/metapac][metapac]] is a declarative wrapper around different package managers, including [[https://wiki.archlinux.org/title/Pacman][pacman]] and [[https://github.com/Morganamilo/paru][paru]]. This means the required packages can be listed in configuration files and checked into version control.

I've also tried [[https://github.com/kiviktnm/decman][decman]], but it turned out to be too unstable because it ships its own logic for building AUR packages, which doesn't always work. So wrapping =paru= seems like a saner approach. Also, sometimes AUR drops packets, and =decman= can't handle it gracefully.

In =metapac=, packages are listed in "groups", each group being a TOML file stating which package has to be installed by which package manager. I declare groups as Org tables, see the "System configuration" section in Emacs.org.

Below is the table enabling different groups on different hostnames:
#+NAME: metapac-groups
| Profile         | archlinux | weiss | violet | schwarz |
| browsers        | +         | +     | +      | +       |
| console         | +         | +     | +      | +       |
| desktop         | +         | +     | +      | +       |
| desktop-misc    | +         | +     | +      | +       |
| desktop-polybar | +         | +     | +      | +       |
| desktop-rofi    | +         | +     | +      | +       |
| dev             | +         | +     | +      | +       |
| emacs           | +         | +     | +      | +       |
| latex           | +         | +     | +      | +       |
| mail            | +         | +     | +      | +       |
| music           | +         | +     | +      | +       |
| nvidia          |           |       | +      |         |
| office          | +         | +     | +      | +       |
| system          | +         | +     | +      | +       |
| printer         |           |       | +      |         |
| games           |           |       | +      |         |
| geo             |           |       | +      |         |

And the code to format it as TOML:
#+NAME: metapac-groups-format
#+begin_src emacs-lisp :var groups=metapac-groups
(let* ((hostnames (cdr (nth 0 groups)))
       groups-by-hostname)
  (cl-loop for row in (cdr groups)
           for group = (nth 0 row)
           do (cl-loop for i from 0
                       for sign in (cdr row)
                       for hostname = (nth i hostnames)
                       if (not (string-empty-p sign))
                       do (push group (alist-get hostname groups-by-hostname
                                                 nil nil #'equal))))
  (cl-loop for (hostname . groups) in groups-by-hostname
           concat (format "%s = [%s]\n" hostname
                          (mapconcat (lambda (g) (format "\"%s\"" g)) groups ","))))
#+end_src

Which is used in the config:
#+begin_src toml :tangle .config/metapac/config.toml :noweb yes
enabled_backends = ["arch", "flatpak"]
hostname_groups_enabled = true

[hostname_groups]
<<metapac-groups-format()>>

[arch]
package_manager = "paru"
#+end_src

* pacserve
https://wiki.archlinux.org/title/Pacserve

| Arch dependencies |
|-------------------|
| pacserve          |

#+begin_src bash
systemctl enable --now pacserve
#+end_src

* System packages
Some necessary Arch packages:
| Arch dependency     |
|---------------------|
| amneziavpn-bin      |
| base                |
| base-devel          |
| debtap              |
| grub                |
| iwd                 |
| lightdm             |
| lightdm-gtk-greeter |
| linux               |
| linux-firmware      |
| inetutils           |
| nano                |
| networkmanager      |
| metapac             |
| openssh             |
| pacman-contrib      |
| paru                |
| pipewire            |
| pipewire-audio      |
| pipewire-alsa       |
| pipewire-pulse      |
| pipewire-jack       |
| sof-firmware        |
| smartmontools       |
| vim                 |
| xterm               |
| wget                |
| wireless_tools      |
| wireplumber         |
| yadm                |
| zram-generator      |

Various drivers, I'm not sure which I actually need, so...
| Arch dependency    |
|--------------------|
| libva-intel-driver |
| intel-media-driver |
| vulkan-intel       |
| vulkan-radeon      |
| xf86-video-amdgpu  |
| xf86-video-ati     |

Also [[https://github.com/evilsocket/opensnitch][opensnitch]], a firewall.

| Arch dependency |
|-----------------|
| opensnitch      |

A tool to downgrade a package.
| Arch dependency |
|-----------------|
| downgrade       |

NVIDIA drivers & AI stuff for violet
| Category | Arch dependency          |
|----------+--------------------------|
| nvidia   | cuda                     |
| nvidia   | nvidia-utils             |
| nvidia   | nvidia-open              |
| nvidia   | ollama-cuda              |
| nvidia   | nvidia-container-toolkit |

Printer packages.
| Category | Arch dependency |
|----------+-----------------|
| printer  | cups            |
| printer  | usbutils        |
| printer  | brlaser         |
| printer  | naps2-bin       |
| printer  | brscan4         |

#+NAME: packages
#+begin_src emacs-lisp :tangle no :var category=""
(my/format-arch-dependencies category)
#+end_src

#+begin_src scheme :tangle .config/metapac/groups/nvidia.toml :noweb yes
<<packages("nvidia")>>
#+end_src

#+begin_src scheme :tangle .config/metapac/groups/printer.toml :noweb yes
<<packages("printer")>>
#+end_src

#+begin_src scheme :tangle .config/metapac/groups/system.toml :noweb yes
<<packages()>>
#+end_src

* Notes on VMs
** Linux
Install spice-vdagent and reboot to enable clipboard sharing.

Check View > Scale Display > Auto resize VM with window. Then, running
#+begin_src bash
xrandr --output Virtual-1 --auto
#+end_src
Will resize the display to the VM window. [[https://superuser.com/questions/1183834/no-auto-resize-with-spice-and-virt-manager][This question]] has some info on how to automate that, I'm fine with executing the command manually.

To add a shared folder, do:
- Memory > Enable shared memory
- Add hardware > Filesystem with virtiofs, e.g.

#+begin_src xml
<filesystem type="mount">
  <source dir="/home/pavel/00-Scratch"/>
  <target dir="shared"/>
  <driver type="virtiofs"/>
</filesystem>
#+end_src

Then, in order to mount:
#+begin_src bash
mkdir ~/00-Scratch/
sudo mount -t virtiofs shared /home/pavel/00-Scratch/
#+end_src

To make in permanent, add the following to =/etc/fstab=
#+begin_src
shared /home/pavel/00-Scratch virtiofs defaults 0 0
#+end_src
** Copying VMs between machines
To copy a VM, first, copy the image:
#+begin_src bash
rsync -avP /var/lib/libvirt/images/debian12-vpn.qcow2 /run/media/pavel/A6E5-4138/vms/
#+end_src

Then, export the configuration:
#+begin_src
virsh -c qemu:///system dumpxml debian12-vpn > debian12-vpn.xml
#+end_src

To restore, copy the image back:
#+begin_src bash
sudo rsync -avP /run/media/pavel/A6E5-4138/vms/debian12-vpn.qcow2 /var/lib/libvirt/images/
#+end_src

And import the configuration:
#+begin_src src
sudo virsh define debian12-vpn.xml
#+end_src
** Assign a static IP to a VM
To assign a static IP to a VM, run:
#+begin_src bash
sudo EDITOR=vim virsh net-edit default
#+end_src

And inside the =<dhcp>= section, insert:
#+begin_src bash
<host mac='52:54:00:58:7f:82' name='myvm' ip='192.168.122.50'/>
#+end_src

After which, restart the network:
#+begin_src bash
sudo virsh net-destroy default
sudo virsh net-start default
#+end_src
** Network

Don't forget to set =iptables= in =/etc/libvirt/network.conf=:
#+begin_src conf-space
firewall_backend = "iptables"
#+end_src
* Notes on Software
** Upgrading Python and AUR packages
After upgrading Python from 3.13 to 3.14, [[https://aur.archlinux.org/packages/lieer-git][lieer]] has stopped working

#+begin_example
$ gmi
Traceback (most recent call last):
  File "/usr/bin/gmi", line 20, in <module>
    from lieer import Gmailieer
ModuleNotFoundError: No module named 'lieer'
#+end_example

The issue is that the package has been installed for Python 3.13:
#+begin_example
pacman -Ql lieer-git | grep -E '\.py$|site-packages'
lieer-git /usr/lib/python3.13/site-packages/
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/METADATA
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/RECORD
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/WHEEL
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/licenses/
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/licenses/COPYING.GPL-3.0+
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/licenses/LICENSE.md
lieer-git /usr/lib/python3.13/site-packages/lieer-1.6.dist-info/top_level.txt
lieer-git /usr/lib/python3.13/site-packages/lieer/
lieer-git /usr/lib/python3.13/site-packages/lieer/__init__.py
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/__init__.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/__init__.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/gmailieer.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/gmailieer.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/local.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/local.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/nobar.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/nobar.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/remote.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/remote.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/resume.cpython-313.opt-1.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/__pycache__/resume.cpython-313.pyc
lieer-git /usr/lib/python3.13/site-packages/lieer/gmailieer.py
lieer-git /usr/lib/python3.13/site-packages/lieer/local.py
lieer-git /usr/lib/python3.13/site-packages/lieer/nobar.py
lieer-git /usr/lib/python3.13/site-packages/lieer/remote.py
lieer-git /usr/lib/python3.13/site-packages/lieer/resume.py
#+end_example

And the Python version is 3.14:
#+begin_example
$ python --version
Python 3.14.2
#+end_example

Simply rebuilding the package doesn't help because something has been cached. It is neccessary to use the =--rebuild= tag:
#+begin_example
$ paru -S lieer-git --rebuild
#+end_example
** Installing MS Office 2007
MS Office 2007, which I need for work, installs reasonably well on PlayOnLinux, except for one library that can be downloaded with winetricks:

#+begin_src bash
WINEPREFIX=~/.PlayOnLinux/wineprefix/Office2007 WINE=~/.PlayOnLinux/wine/linux-x86/4.0/bin/wine winetricks msxml3
#+end_src
