arch = {
  packages = [
    "texinfo",
    "the_silver_searcher",
    "ripgrep",
    "hledger",
    "rclone",
    "gnu-free-fonts",
    "ttf-unifont",
    "telegram-tdlib",
    "yt-dlp",
    "mpv",
    "ttf-opensans",
    "gvfs-goa",
    "gvfs-dnssd",
    "graphviz",
    "python-isort",
    "python-black",
    "yapf",
    "plantuml",
    "difftastic",
    "xkb-switch",
    "sqrt-emacs",
  ],
}

